#!/bin/sh
librewolf -CreateProfile "main /home/orion/.librewolf/main"

git clone https://github.com/arkenfox/user.js

cp user.js/user.js ~/.librewolf/main &
cp user.js/prefsCleaner.sh ~/.librewolf/main &
cp user.js/updater.sh ~/.librewolf/main &
cp .mozilla/user-overrides.js ~/.librewolf/main
/bin/rm -rf user.js &

cd ~/.librewolf/main
./prefsCleaner.sh
./updater.sh

systemctl --user enable --now psd.service

librewolf about:profiles https://addons.mozilla.org/en-US/firefox/addon/ff2mpv/ https://addons.mozilla.org/en-US/firefox/addon/darkreader/ https://addons.mozilla.org/en-US/firefox/addon/libredirect/ https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/ https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/ https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ https://addons.mozilla.org/en-US/firefox/addon/stack-overflow-prettifier/ -P main
