syntax on
filetype plugin on
filetype indent on

set number relativenumber
set incsearch
set hlsearch
set smartindent
set autoindent
set hidden

noremap jj <nop>
inoremap jk <ESC>
let mapleader = ""
set noswapfile 
set ignorecase
set tabstop=4
set shiftwidth=4
set clipboard=unnamedplus
set encoding=utf-8
set backspace=indent,eol,start

set viminfo='10,<100,:100,%,n/$XDG_CONFIG_HOME/vim/viminfo
set ttimeoutlen=10

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif
highlight LineNr ctermfg=grey
