#!/bin/sh
bspc rule -r "*"

SCR=$(xrandr -q | grep ' connected ' | awk '{print $1}')
PRI=$(echo $SCR | awk '{print $1}')
if [ "$SCR" = "$PRI" ]; then
	bspc monitor $PRI -d 1 2 3 4 5 6 7 8 9 0 &
	xrandr --auto &
else
	bspc monitor $PRI -d 1 2 3 4 5 &
	SEC=$(echo $SCR | awk '{print $2}')
	bspc monitor $SEC -d 6 7 8 9 0 &
	xrandr --output $PRI --auto --output $SEC --primary --auto --left-of $PRI &
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm --adopt-orphans &

bspc config border_width 1 &
bspc config window_gap 1 &

bspc config split_ratio 0.5 &
bspc config borderless_monocle true &
bspc config gapless_monocle true &
bspc config remove_unplugged_monitors true &
bspc config focus_follows_pointer true &
bspc config paddingless_monocle true &
bspc config single_monocle false &
bspc config focus_follows_pointer true &

bspc rule -a Surf state=tiled &
bspc rule -a Zathura state=tiled &

wmname bspwm &
feh --no-fehbg --bg-fill ~/.config/bg.png
xsetroot -cursor_name left_ptr 
#noisetorch -i
