#!/bin/sh
bspc monitor DP-0 -d 1 2 3 4 5 & 
bspc monitor HDMI-0 -d 6 7 8 9 0 &

xrandr --output DP-0 --primary --mode 1920x1080 -r 144.00 --output HDMI-0 --mode 1920x1080 -r 50.00 --right-of DP-0 & 

bspc config border_width         1 &
bspc config window_gap           1 &

bspc config split_ratio               0.5 &
bspc config borderless_monocle        true &
bspc config gapless_monocle           true &
bspc config remove_unplugged_monitors true &
bspc config focus_follows_pointer     true &

bspc rule -a Surf state=tiled &
bspc rule -a Zathura state=tiled &

bspc config normal_border_color "#44475a" &
bspc config active_border_color "#6272a4" &
bspc config focused_border_color "#8be9fd" &
bspc config presel_feedback_color "#6272a4" &

killall -q sxhkd; sxhkd &
xsetroot -cursor_name left_ptr &
wmname LG3D 
#feh --no-fehbg --bg-fill '/usr/share/backgrounds/archlinux/awesome.png'
