#!/bin/sh
bspc rule -r "*"

#bspc monitor DP-0 -d 1 2 3 4 5 &
#bspc monitor DP-2 -d 6 7 8 9 0 &
#xrandr --output DP-0 --auto -r 180 --primary --output DP-2 --auto -r 50 --right-of DP-0 &

SCR=$(xrandr -q | grep ' connected ' | awk '{print $1}')
PRI=$(echo $SCR | awk '{print $1}')
if [ "$SCR" = "$PRI" ]; then
	bspc monitor $PRI -d 1 2 3 4 5 6 7 8 9 0 &
	xrandr --auto &
else
	bspc monitor $PRI -d 1 2 3 4 5 &
	SEC=$(echo $SCR | awk '{print $2}')
	bspc monitor $SEC -d 6 7 8 9 0 &
	xrandr --output $PRI --auto --output $SEC --primary --auto --left-of $PRI &
    setxkbmap it
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm --adopt-orphans &

bspc config split_ratio 0.52 &
bspc config remove_unplugged_monitors true &
bspc config remove_disabled_monitors true &
bspc config merge_overlapping_monitors true &
bspc config focus_follows_pointer true &
bspc config pointer_follows_monitor true &
bspc config pointer_modifier mod1 &
bspc config pointer_action1 move &
bspc config pointer_action2 resize_side &
bspc config pointer_action3 resize_corner &

bspc config window_gap 1 &
bspc config focused_border_color "#e42022" &

bspc rule -a Zathura state=tiled &

wmname bspwm &
xsetroot -cursor_name left_ptr
